spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookreviews-books

server:
  port: 8082

jwt:
  secret: "EnunLugardelamanchadecuyonombrenoquieroacordarmeviviaunhidalgo"
  expiration: 3600000
