spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookreviews-users

server:
  port: 8081

jwt:
  secret: "EnunLugardelamanchadecuyonombrenoquieroacordarmeviviaunhidalgo"
  expiration: 3600000
