spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookreviews-reviews

server:
  port: 8083

jwt:
  secret: "EnunLugardelamanchadecuyonombrenoquieroacordarmeviviaunhidalgo"
  expiration: 3600000
